name: Docker build and push to custom docker registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]




jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}       
      -
        name: Login to Custom registry 
        uses: docker/login-action@v1 
        with:
          registry: cloud.canister.io:5000
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            cloud.canister.io:5000/locohamster/loco_exporter
            cloud.canister.io:5000/locohamster/loco_exporter:${{ steps.buildnumber.outputs.build_number }}
      - 
        name: Print tags
        run: echo "Image pushed to ${{ steps.meta.outputs.tags }}"
      -
        name: Print image url
        run: cloud.canister.io:5000/locohamster/loco_exporter:${{ steps.buildnumber.outputs.build_number }}


   
  
